### ISSUE TITLE
More documentation & examples

### ISSUE THREAD

**Issue by choubacha** [jvff/serde-xdr#1]
I'm just getting started with this library and trying to figure out what rust types map to xdr types is a little difficult without reading code. I believe that most serde types just work but it would be nice for this to be documented in the rust docs.

**Comment by jvff** [comment]
I've updated the README to include a [table](https://github.com/jvff/serde-xdr/tree/master#data-type-map) documenting the types and their mappings.

Thanks for the request!

If you believe this resolves your issue, please consider closing it. Otherwise, please add more details as a comment below.

**Comment by choubacha** [comment]
Yes, very much so!
