### ISSUE TITLE
Interoperability with existing XDR service

### ISSUE THREAD

**Issue by calderonth** [jvff/serde-xdr#5]
Hello,

I have attempted to use this library along with the `onc-rpc` crate you've developed to interoperate with an existing SunRPC service.

I managed to get some a basic Rust synchronous client/server running with your libraries but when I attempt to use the Rust client with an existing C based server, it doesn't work. From doing differential packet capture it seems that the Rust server is sending 8 more bytes than the C server when returning a basic type (`i64`). So I am assuming that there is some sort of additional wrapping around the values sent on the wire.

Below is the sample program I've used:
```
onc_rpc! {
    program(program_module::MyProgram) {
        id = 0x3;
        version = 4;

        procedures {
            fn(2) testRPC(value: i64) -> testRPCResult<i64>,
        }
    }
}
```

How could I investigate properly/fix this?

Thanks,

**Comment by jvff** [comment]
Hello,

From what you've described, the issue might be that somewhere unnecessary
padding or alignment bytes are being added.

I'm not sure exactly how to isolate the cause, but I'd suggest digging into
the generated message type to see if it is serialized correctly.

`cargo expand` might be useful here to see the generated types (although it
will print out a lot of code).

I'll probably have some time in the weekend to dig deeper in this and see
if I can help finding the issue :)

Thanks for the report and for providing a reproducible example of the issue!

Janito

**Comment by calderonth** [comment]
Hello,

I've managed to get more details and turns out I had switched Program/Version numbers, so the basic logic does work.

**Comment by calderonth** [comment]
Hm I'm actually now facing other issues with serialization, the basic types were fine but it seems the more complex ones don't work :-/

**Comment by jvff** [comment]
Hello,

Ok, cool. Do you have an example of a type that's not working correctly?

Thanks,

Janito

**Comment by calderonth** [comment]
If we assume a simple RPC that returns a `my_result` defined as follows in a XDR file:
```
struct st_info {
  opaque major<1>;
  opaque minor<1>;
};
struct my_result {
  hyper rv; 
  st_info info;
}
```
I am unable to use your library to properly retrieve the result, I think this might be due to the `opaque` type where it doesn't properly allow for reading a single byte as the `major`/`minor`. However this is valid XDR syntax/format.

For instance another ONC-RPC/XDR library https://github.com/domodwyer/onc-rpc I am able to properly parse this syntax, the raw payload would be as follows:
```
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 40]
```
Where `rv = 0` and `major = 2`, `minor = 40`
And when using the Unpack method, the structure is properly parsed/deserialized:
```
my_result { rv: 0, st_info: { major: [2], minor: [40] } }
```

I've attempted to use the following RPC definition to parse with your library but that fails:
```
#[derive(Serialize, Deserialize, PartialEq, Debug)]
pub struct st_info {
  pub major: Vec<u8>,
  pub minor: Vec<u8>,
}
#[derive(Serialize, Deserialize, PartialEq, Debug)]
pub struct my_result {
  pub rv: i64,
  pub info: st_info,
}
```

I've also tried to use `#[serde(with = "serde_xdr::opaque_data::fixed_length")]` but it didn't help much.

Any idea what I'm doing wrong?

Thanks

**Comment by jvff** [comment]
Hello,

I think in this case you'd have to use a `[u8; 1]` as the field type and
also use the `serde(with = "serde_xdr::opaque_data::fixed_length")`
serialization attribute.

Let me know if that works :)

Thanks,

Janito

**Comment by calderonth** [comment]
I had tried this but get the following error:

```
Err(Error(ProcedureCallError("CGetInfo"), State { next_error: Some(Error(XdrError(DeserializeFailure("struct field RpcMessage::body")), State { next_error: Some(Error(DeserializeFailure("enum variant RpcBody::Reply"), State { next_error: Some(Error(DeserializeFailure("enum variant ReplyBody::Accepted"), State { next_error: Some(Error(DeserializeFailure("struct field AcceptedReply::reply_data"), State { next_error: Some(Error(DeserializeFailure("enum variant AcceptedStatus::Success"), State { next_error: Some(Error(DeserializeFailure("struct field my_result::info"), State { next_error: Some(Error(DeserializeFailure("struct field st_info::minor"), State { next_error: Some(Error(DeserializeFailure("element 0 of type tuple"), State { next_error: Some(Error(InvalidUnsignedInteger(8, 33554432), State { next_error: None, backtrace: None })), backtrace: None })), backtrace: None })), backtrace: None })), backtrace: None })), backtrace: None })), backtrace: None })), backtrace: None })), backtrace: None })), backtrace: None }))
```
The value `33554432` is coming from `0x2000000` but it must be parsing it wrong as it's reading beyond of the single byte that should be read?

**Comment by calderonth** [comment]
So from the specification variable opaque data are 4-byte aligned and padded with 0 appropriately.
And if defining `[u8; 1]`, it should be ignoring the following 3 bytes of padding.
Does that make sense?

**Comment by jvff** [comment]
Right, sorry. I got confused and thought that it was a fixed-length opaque
data. It's actually variable-length, and for that you'll need to force
serde to serialize the data as bytes instead of a sequence of `u8`s (which
would add padding bytes per element of the vector). So you'll have to use
the `serde_bytes` crate to serialize and deserialize that field:

```
#[derive(Serialize, Deserialize, PartialEq, Debug)]
pub struct st_info {
   #[serde(with = "serde_bytes")]
  pub major: Vec<u8>,
   #[serde(with = "serde_bytes")]
   pub minor: Vec<u8>,
}
```

Note that for this to work, I had to make sure that the raw payload had the
proper 4-byte alignment, so I added 3 zeros to the end of the payload bytes
you provided.

Hope this helps :)

Janito

**Comment by jvff** [comment]
> So from the specification variable opaque data are 4-byte aligned and padded with 0 appropriately.
> And if defining `[u8; 1]`, it should be ignoring the following 3 bytes of padding.
> Does that make sense?

Yes, but specifying it as `[u8; 1]` will make it use a fixed-length, and that doesn't get treated as variable-length opaque data :/ But the same logic applies, it still needs to be padded with zeros to a 4-byte alignment, but the padding is discarded when deserializing.

**Comment by calderonth** [comment]
Ha! That was it it's now parsing properly.

Thanks for your help debugging this!

**Comment by jvff** [comment]
That's great to hear! Glad I was able to help a bit :D
